# Generated by Django 5.0.7 on 2024-07-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_team_points_team_wins_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchup_winner', to='myapp.team'),
        ),
        migrations.AddField(
            model_name='race',
            name='fastest_lap_constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastest_lap_races', to='myapp.constructor'),
        ),
        migrations.AddField(
            model_name='race',
            name='fastest_lap_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fastest_lap_races', to='myapp.driver'),
        ),
    ]
