# Generated by Django 5.0.7 on 2024-07-16 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_scoringrule_raceresult_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='fastest_lap_constructor',
        ),
        migrations.RemoveField(
            model_name='race',
            name='fastest_lap_driver',
        ),
    ]
